# Common paths
INPUT_SIM := input/simulation
CONFIG_DIR := $(INPUT_SIM)/configs/architecture_explorer
HARDWARE_REF := $(INPUT_SIM)/hardware_reference
SYNTHESIS := $(INPUT_SIM)/synthesis
LAYER_DIR := $(INPUT_SIM)/layer

# Test options
TEST_OPTION_MULT := $(CONFIG_DIR)/hbm2_total_multiplier_16384.cfg
TEST_OPTION_OFF_CHIP_MEM_REF := $(HARDWARE_REF)/DRAMsim3/hbm2.cfg
TEST_OPTION_SRAM_REF := $(HARDWARE_REF)/nvsim/sram.cfg
TEST_OPTION_RTL_RESULT_REF := $(SYNTHESIS)/weight.bin

# Define layer model (can be easily changed)
MODEL := mobilenet
MODEL_VARIANT := v2

# Layer configuration paths (generic format)
LAYER_PATH := $(LAYER_DIR)/$(MODEL)
VARIANT_PATH := $(LAYER_PATH)/$(MODEL_VARIANT)

CONV1 := $(VARIANT_PATH)/conv1.cfg

STAGE1_BLOCK1_DEPTHWISE := $(VARIANT_PATH)/stage1_block1_depthwise.cfg
STAGE1_BLOCK1_PROJECTION := $(VARIANT_PATH)/stage1_block1_projection.cfg

STAGE2_BLOCK1_DEPTHWISE := $(VARIANT_PATH)/stage2_block1_depthwise.cfg
STAGE2_BLOCK1_PROJECTION := $(VARIANT_PATH)/stage2_block1_projection.cfg
STAGE2_BLOCK1_BOTTLENECK := $(VARIANT_PATH)/stage2_block1_bottleneck.cfg

STAGE2_BLOCK2_DEPTHWISE := $(VARIANT_PATH)/stage2_block2_depthwise.cfg
STAGE2_BLOCK2_PROJECTION := $(VARIANT_PATH)/stage2_block2_projection.cfg
STAGE2_BLOCK2_BOTTLENECK := $(VARIANT_PATH)/stage2_block2_bottleneck.cfg

STAGE3_BLOCK1_DEPTHWISE := $(VARIANT_PATH)/stage3_block1_depthwise.cfg
STAGE3_BLOCK1_PROJECTION := $(VARIANT_PATH)/stage3_block1_projection.cfg
STAGE3_BLOCK1_BOTTLENECK := $(VARIANT_PATH)/stage3_block1_bottleneck.cfg

STAGE3_BLOCK2_DEPTHWISE := $(VARIANT_PATH)/stage3_block2_depthwise.cfg
STAGE3_BLOCK2_PROJECTION := $(VARIANT_PATH)/stage3_block2_projection.cfg
STAGE3_BLOCK2_BOTTLENECK := $(VARIANT_PATH)/stage3_block2_bottleneck.cfg

STAGE3_BLOCK3_DEPTHWISE := $(VARIANT_PATH)/stage3_block3_depthwise.cfg
STAGE3_BLOCK3_PROJECTION := $(VARIANT_PATH)/stage3_block3_projection.cfg
STAGE3_BLOCK3_BOTTLENECK := $(VARIANT_PATH)/stage3_block3_bottleneck.cfg

STAGE4_BLOCK1_DEPTHWISE := $(VARIANT_PATH)/stage4_block1_depthwise.cfg
STAGE4_BLOCK1_PROJECTION := $(VARIANT_PATH)/stage4_block1_projection.cfg
STAGE4_BLOCK1_BOTTLENECK := $(VARIANT_PATH)/stage4_block1_bottleneck.cfg

STAGE4_BLOCK2_DEPTHWISE := $(VARIANT_PATH)/stage4_block2_depthwise.cfg
STAGE4_BLOCK2_PROJECTION := $(VARIANT_PATH)/stage4_block2_projection.cfg
STAGE4_BLOCK2_BOTTLENECK := $(VARIANT_PATH)/stage4_block2_bottleneck.cfg

STAGE4_BLOCK3_DEPTHWISE := $(VARIANT_PATH)/stage4_block3_depthwise.cfg
STAGE4_BLOCK3_PROJECTION := $(VARIANT_PATH)/stage4_block3_projection.cfg
STAGE4_BLOCK3_BOTTLENECK := $(VARIANT_PATH)/stage4_block3_bottleneck.cfg

STAGE4_BLOCK4_DEPTHWISE := $(VARIANT_PATH)/stage4_block4_depthwise.cfg
STAGE4_BLOCK4_PROJECTION := $(VARIANT_PATH)/stage4_block4_projection.cfg
STAGE4_BLOCK4_BOTTLENECK := $(VARIANT_PATH)/stage4_block4_bottleneck.cfg

STAGE5_BLOCK1_DEPTHWISE := $(VARIANT_PATH)/stage5_block1_depthwise.cfg
STAGE5_BLOCK1_PROJECTION := $(VARIANT_PATH)/stage5_block1_projection.cfg
STAGE5_BLOCK1_BOTTLENECK := $(VARIANT_PATH)/stage5_block1_bottleneck.cfg

STAGE5_BLOCK2_DEPTHWISE := $(VARIANT_PATH)/stage5_block2_depthwise.cfg
STAGE5_BLOCK2_PROJECTION := $(VARIANT_PATH)/stage5_block2_projection.cfg
STAGE5_BLOCK2_BOTTLENECK := $(VARIANT_PATH)/stage5_block2_bottleneck.cfg

STAGE5_BLOCK3_DEPTHWISE := $(VARIANT_PATH)/stage5_block3_depthwise.cfg
STAGE5_BLOCK3_PROJECTION := $(VARIANT_PATH)/stage5_block3_projection.cfg
STAGE5_BLOCK3_BOTTLENECK := $(VARIANT_PATH)/stage5_block3_bottleneck.cfg

STAGE6_BLOCK1_DEPTHWISE := $(VARIANT_PATH)/stage6_block1_depthwise.cfg
STAGE6_BLOCK1_PROJECTION := $(VARIANT_PATH)/stage6_block1_projection.cfg
STAGE6_BLOCK1_BOTTLENECK := $(VARIANT_PATH)/stage6_block1_bottleneck.cfg

STAGE6_BLOCK2_DEPTHWISE := $(VARIANT_PATH)/stage6_block2_depthwise.cfg
STAGE6_BLOCK2_PROJECTION := $(VARIANT_PATH)/stage6_block2_projection.cfg
STAGE6_BLOCK2_BOTTLENECK := $(VARIANT_PATH)/stage6_block2_bottleneck.cfg

STAGE6_BLOCK3_DEPTHWISE := $(VARIANT_PATH)/stage6_block3_depthwise.cfg
STAGE6_BLOCK3_PROJECTION := $(VARIANT_PATH)/stage6_block3_projection.cfg
STAGE6_BLOCK3_BOTTLENECK := $(VARIANT_PATH)/stage6_block3_bottleneck.cfg

STAGE7_BLOCK1_DEPTHWISE := $(VARIANT_PATH)/stage7_block1_depthwise.cfg
STAGE7_BLOCK1_PROJECTION := $(VARIANT_PATH)/stage7_block1_projection.cfg
STAGE7_BLOCK1_BOTTLENECK := $(VARIANT_PATH)/stage7_block1_bottleneck.cfg

CONV_LAST := $(VARIANT_PATH)/conv_last.cfg
FC := $(VARIANT_PATH)/fc.cfg

# Common arguments for all SBT runs
COMMON_ARGS := $(TEST_OPTION_MULT) $(TEST_OPTION_OFF_CHIP_MEM_REF) $(TEST_OPTION_SRAM_REF) $(TEST_OPTION_RTL_RESULT_REF)

# Define targets for specific layers
.PHONY: conv1 stage1 stage2 stage3 stage4 stage5 stage6 stage7 conv_last fc

# Default target runs all configurations for the specified model/variant
all: conv1 stage1 stage2 stage3 stage4 stage5 stage6 stage7 conv_last fc

# Target to run a specific layer model

conv1:
	sbt "runMain simulation.SystemArchitectureOptimizer $(CONV1) $(COMMON_ARGS)"

stage1:
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE1_BLOCK1_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE1_BLOCK1_PROJECTION) $(COMMON_ARGS)"

stage2:
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE2_BLOCK1_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE2_BLOCK1_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE2_BLOCK1_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE2_BLOCK2_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE2_BLOCK2_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE2_BLOCK2_PROJECTION) $(COMMON_ARGS)"

stage3:
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK1_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK1_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK1_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK2_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK2_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK2_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK3_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK3_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE3_BLOCK3_PROJECTION) $(COMMON_ARGS)"

stage4:
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK1_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK1_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK1_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK2_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK2_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK2_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK3_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK3_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK3_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK4_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK4_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE4_BLOCK4_PROJECTION) $(COMMON_ARGS)"

stage5:
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK1_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK1_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK1_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK2_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK2_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK2_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK3_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK3_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE5_BLOCK3_PROJECTION) $(COMMON_ARGS)"

stage6:
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK1_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK1_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK1_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK2_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK2_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK2_PROJECTION) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK3_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK3_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE6_BLOCK3_PROJECTION) $(COMMON_ARGS)"

stage7:
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE7_BLOCK1_BOTTLENECK) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE7_BLOCK1_DEPTHWISE) $(COMMON_ARGS)"
	sbt "runMain simulation.SystemArchitectureOptimizer $(STAGE7_BLOCK1_PROJECTION) $(COMMON_ARGS)"

conv_last:
	sbt "runMain simulation.SystemArchitectureOptimizer $(CONV_LAST) $(COMMON_ARGS)"

fc:
	sbt "runMain simulation.SystemArchitectureOptimizer $(FC) $(COMMON_ARGS)"