rtl_gen:
	#sbt "runMain rtl.Main input/rtl/is_16x8x1x4x2.cfg"
	#sbt "runMain rtl.Main input/rtl/is_64x32x1x1x1.cfg"
	sbt "runMain rtl.Main input/rtl/os_8x128x1x1x1.cfg"
	sbt "runMain rtl.Main input/rtl/os_16x32x2x1x2.cfg"
	#sbt "runMain rtl.Main input/rtl/ws_16x16x2x2x1.cfg"
	#sbt "runMain rtl.Main input/rtl/ws_32x16x1x1x4.cfg"
	#sbt "runMain rtl.Main input/rtl/output_stationary.cfg"


