
BASE_CONFIG_PATH := input/simulation/configs/architecture_explorer
LAYER_RESNET50_CONV2_1x1 := input/simulation/layer/resnet18/stage4_block1_shortcut.cfg
TEST_OPTION_1024 = $(BASE_CONFIG_PATH)/ddr4_total_multiplier_1024.cfg

TEST_OPTION_DRAM_REF := input/simulation/hardware_reference/DRAMsim3/ddr4_dram.cfg
TEST_OPTION_SRAM_REF := input/simulation/hardware_reference/nvsim/sram.cfg
TEST_OPTION_RTL_RESULT_REF := input/simulation/synthesis/weight.bin

.PHONY: run
run:
	sbt "runMain simulation.SystemArchitectureOptimizer ${LAYER_RESNET50_CONV2_1x1} ${TEST_OPTION_1024} ${TEST_OPTION_DRAM_REF} ${TEST_OPTION_SRAM_REF} ${TEST_OPTION_RTL_RESULT_REF}"


