.PHONY: all
all:
	make -f Makefile.optimizer_bert_all all
	make -f Makefile.optimier_bloom_1b all
	make -f Makefile.optimier_falcon_1b all
	make -f Makefile.optimier_phi_2 all
	make -f Makefile.optimier_llama_3b all
	make -f Makefile.optimier_mistral_7b all


