// Generated by CIRCT firtool-1.62.0
module is_sta_8x8x1x1x1(
  input         clock,
                reset,
  input  [7:0]  io_inputA_0,
                io_inputA_1,
                io_inputA_2,
                io_inputA_3,
                io_inputA_4,
                io_inputA_5,
                io_inputA_6,
                io_inputA_7,
                io_inputB_0,
                io_inputB_1,
                io_inputB_2,
                io_inputB_3,
                io_inputB_4,
                io_inputB_5,
                io_inputB_6,
                io_inputB_7,
  input         io_propagateA_0,
                io_propagateA_1,
                io_propagateA_2,
                io_propagateA_3,
                io_propagateA_4,
                io_propagateA_5,
                io_propagateA_6,
                io_propagateA_7,
  output [18:0] io_outputC_0,
                io_outputC_1,
                io_outputC_2,
                io_outputC_3,
                io_outputC_4,
                io_outputC_5,
                io_outputC_6,
                io_outputC_7
);

  wire [18:0] _systolicTensorArray_io_outputC_0;
  wire [18:0] _systolicTensorArray_io_outputC_1;
  wire [18:0] _systolicTensorArray_io_outputC_2;
  wire [18:0] _systolicTensorArray_io_outputC_3;
  wire [18:0] _systolicTensorArray_io_outputC_4;
  wire [18:0] _systolicTensorArray_io_outputC_5;
  wire [18:0] _systolicTensorArray_io_outputC_6;
  wire [18:0] _systolicTensorArray_io_outputC_7;
  wire [7:0]  _preProcessorInputB_io_output_0;
  wire [7:0]  _preProcessorInputB_io_output_1;
  wire [7:0]  _preProcessorInputB_io_output_2;
  wire [7:0]  _preProcessorInputB_io_output_3;
  wire [7:0]  _preProcessorInputB_io_output_4;
  wire [7:0]  _preProcessorInputB_io_output_5;
  wire [7:0]  _preProcessorInputB_io_output_6;
  wire [7:0]  _preProcessorInputB_io_output_7;
  wire [7:0]  _preProcessorInputA_io_output_0;
  wire [7:0]  _preProcessorInputA_io_output_1;
  wire [7:0]  _preProcessorInputA_io_output_2;
  wire [7:0]  _preProcessorInputA_io_output_3;
  wire [7:0]  _preProcessorInputA_io_output_4;
  wire [7:0]  _preProcessorInputA_io_output_5;
  wire [7:0]  _preProcessorInputA_io_output_6;
  wire [7:0]  _preProcessorInputA_io_output_7;
  reg         REG_0;
  reg         REG_1;
  reg         REG_2;
  reg         REG_3;
  reg         REG_4;
  reg         REG_5;
  reg         REG_6;
  reg         REG_7;
  always @(posedge clock) begin
    if (reset) begin
      REG_0 <= 1'h0;
      REG_1 <= 1'h0;
      REG_2 <= 1'h0;
      REG_3 <= 1'h0;
      REG_4 <= 1'h0;
      REG_5 <= 1'h0;
      REG_6 <= 1'h0;
      REG_7 <= 1'h0;
    end
    else begin
      REG_0 <= io_propagateA_0;
      REG_1 <= io_propagateA_1;
      REG_2 <= io_propagateA_2;
      REG_3 <= io_propagateA_3;
      REG_4 <= io_propagateA_4;
      REG_5 <= io_propagateA_5;
      REG_6 <= io_propagateA_6;
      REG_7 <= io_propagateA_7;
    end
  end // always @(posedge)
  pre_processor_a preProcessorInputA (
    .clock       (clock),
    .reset       (reset),
    .io_input_0  (io_inputA_0),
    .io_input_1  (io_inputA_1),
    .io_input_2  (io_inputA_2),
    .io_input_3  (io_inputA_3),
    .io_input_4  (io_inputA_4),
    .io_input_5  (io_inputA_5),
    .io_input_6  (io_inputA_6),
    .io_input_7  (io_inputA_7),
    .io_output_0 (_preProcessorInputA_io_output_0),
    .io_output_1 (_preProcessorInputA_io_output_1),
    .io_output_2 (_preProcessorInputA_io_output_2),
    .io_output_3 (_preProcessorInputA_io_output_3),
    .io_output_4 (_preProcessorInputA_io_output_4),
    .io_output_5 (_preProcessorInputA_io_output_5),
    .io_output_6 (_preProcessorInputA_io_output_6),
    .io_output_7 (_preProcessorInputA_io_output_7)
  );
  pre_processor_b preProcessorInputB (
    .clock       (clock),
    .reset       (reset),
    .io_input_0  (io_inputB_0),
    .io_input_1  (io_inputB_1),
    .io_input_2  (io_inputB_2),
    .io_input_3  (io_inputB_3),
    .io_input_4  (io_inputB_4),
    .io_input_5  (io_inputB_5),
    .io_input_6  (io_inputB_6),
    .io_input_7  (io_inputB_7),
    .io_output_0 (_preProcessorInputB_io_output_0),
    .io_output_1 (_preProcessorInputB_io_output_1),
    .io_output_2 (_preProcessorInputB_io_output_2),
    .io_output_3 (_preProcessorInputB_io_output_3),
    .io_output_4 (_preProcessorInputB_io_output_4),
    .io_output_5 (_preProcessorInputB_io_output_5),
    .io_output_6 (_preProcessorInputB_io_output_6),
    .io_output_7 (_preProcessorInputB_io_output_7)
  );
  systolic_tensor_array systolicTensorArray (
    .clock           (clock),
    .reset           (reset),
    .io_inputA_0     (_preProcessorInputA_io_output_0),
    .io_inputA_1     (_preProcessorInputA_io_output_1),
    .io_inputA_2     (_preProcessorInputA_io_output_2),
    .io_inputA_3     (_preProcessorInputA_io_output_3),
    .io_inputA_4     (_preProcessorInputA_io_output_4),
    .io_inputA_5     (_preProcessorInputA_io_output_5),
    .io_inputA_6     (_preProcessorInputA_io_output_6),
    .io_inputA_7     (_preProcessorInputA_io_output_7),
    .io_inputB_0     (_preProcessorInputB_io_output_0),
    .io_inputB_1     (_preProcessorInputB_io_output_1),
    .io_inputB_2     (_preProcessorInputB_io_output_2),
    .io_inputB_3     (_preProcessorInputB_io_output_3),
    .io_inputB_4     (_preProcessorInputB_io_output_4),
    .io_inputB_5     (_preProcessorInputB_io_output_5),
    .io_inputB_6     (_preProcessorInputB_io_output_6),
    .io_inputB_7     (_preProcessorInputB_io_output_7),
    .io_propagateA_0 (REG_0),
    .io_propagateA_1 (REG_1),
    .io_propagateA_2 (REG_2),
    .io_propagateA_3 (REG_3),
    .io_propagateA_4 (REG_4),
    .io_propagateA_5 (REG_5),
    .io_propagateA_6 (REG_6),
    .io_propagateA_7 (REG_7),
    .io_outputC_0    (_systolicTensorArray_io_outputC_0),
    .io_outputC_1    (_systolicTensorArray_io_outputC_1),
    .io_outputC_2    (_systolicTensorArray_io_outputC_2),
    .io_outputC_3    (_systolicTensorArray_io_outputC_3),
    .io_outputC_4    (_systolicTensorArray_io_outputC_4),
    .io_outputC_5    (_systolicTensorArray_io_outputC_5),
    .io_outputC_6    (_systolicTensorArray_io_outputC_6),
    .io_outputC_7    (_systolicTensorArray_io_outputC_7)
  );
  post_processor postProcessor (
    .clock       (clock),
    .reset       (reset),
    .io_input_0  (_systolicTensorArray_io_outputC_0),
    .io_input_1  (_systolicTensorArray_io_outputC_1),
    .io_input_2  (_systolicTensorArray_io_outputC_2),
    .io_input_3  (_systolicTensorArray_io_outputC_3),
    .io_input_4  (_systolicTensorArray_io_outputC_4),
    .io_input_5  (_systolicTensorArray_io_outputC_5),
    .io_input_6  (_systolicTensorArray_io_outputC_6),
    .io_input_7  (_systolicTensorArray_io_outputC_7),
    .io_output_0 (io_outputC_0),
    .io_output_1 (io_outputC_1),
    .io_output_2 (io_outputC_2),
    .io_output_3 (io_outputC_3),
    .io_output_4 (io_outputC_4),
    .io_output_5 (io_outputC_5),
    .io_output_6 (io_outputC_6),
    .io_output_7 (io_outputC_7)
  );
endmodule

