// Generated by CIRCT firtool-1.62.0
module post_processor(
  input         clock,
                reset,
  input  [18:0] io_input_0,
                io_input_1,
                io_input_2,
                io_input_3,
                io_input_4,
                io_input_5,
                io_input_6,
                io_input_7,
  output [18:0] io_output_0,
                io_output_1,
                io_output_2,
                io_output_3,
                io_output_4,
                io_output_5,
                io_output_6,
                io_output_7
);

  reg [18:0] io_output_0_r;
  reg [18:0] io_output_0_r_1;
  reg [18:0] io_output_0_r_2;
  reg [18:0] io_output_0_r_3;
  reg [18:0] io_output_0_r_4;
  reg [18:0] io_output_0_r_5;
  reg [18:0] io_output_0_r_6;
  reg [18:0] io_output_0_r_7;
  reg [18:0] io_output_1_r;
  reg [18:0] io_output_1_r_1;
  reg [18:0] io_output_1_r_2;
  reg [18:0] io_output_1_r_3;
  reg [18:0] io_output_1_r_4;
  reg [18:0] io_output_1_r_5;
  reg [18:0] io_output_1_r_6;
  reg [18:0] io_output_2_r;
  reg [18:0] io_output_2_r_1;
  reg [18:0] io_output_2_r_2;
  reg [18:0] io_output_2_r_3;
  reg [18:0] io_output_2_r_4;
  reg [18:0] io_output_2_r_5;
  reg [18:0] io_output_3_r;
  reg [18:0] io_output_3_r_1;
  reg [18:0] io_output_3_r_2;
  reg [18:0] io_output_3_r_3;
  reg [18:0] io_output_3_r_4;
  reg [18:0] io_output_4_r;
  reg [18:0] io_output_4_r_1;
  reg [18:0] io_output_4_r_2;
  reg [18:0] io_output_4_r_3;
  reg [18:0] io_output_5_r;
  reg [18:0] io_output_5_r_1;
  reg [18:0] io_output_5_r_2;
  reg [18:0] io_output_6_r;
  reg [18:0] io_output_6_r_1;
  reg [18:0] io_output_7_r;
  always @(posedge clock) begin
    if (reset) begin
      io_output_0_r <= 19'h0;
      io_output_0_r_1 <= 19'h0;
      io_output_0_r_2 <= 19'h0;
      io_output_0_r_3 <= 19'h0;
      io_output_0_r_4 <= 19'h0;
      io_output_0_r_5 <= 19'h0;
      io_output_0_r_6 <= 19'h0;
      io_output_0_r_7 <= 19'h0;
      io_output_1_r <= 19'h0;
      io_output_1_r_1 <= 19'h0;
      io_output_1_r_2 <= 19'h0;
      io_output_1_r_3 <= 19'h0;
      io_output_1_r_4 <= 19'h0;
      io_output_1_r_5 <= 19'h0;
      io_output_1_r_6 <= 19'h0;
      io_output_2_r <= 19'h0;
      io_output_2_r_1 <= 19'h0;
      io_output_2_r_2 <= 19'h0;
      io_output_2_r_3 <= 19'h0;
      io_output_2_r_4 <= 19'h0;
      io_output_2_r_5 <= 19'h0;
      io_output_3_r <= 19'h0;
      io_output_3_r_1 <= 19'h0;
      io_output_3_r_2 <= 19'h0;
      io_output_3_r_3 <= 19'h0;
      io_output_3_r_4 <= 19'h0;
      io_output_4_r <= 19'h0;
      io_output_4_r_1 <= 19'h0;
      io_output_4_r_2 <= 19'h0;
      io_output_4_r_3 <= 19'h0;
      io_output_5_r <= 19'h0;
      io_output_5_r_1 <= 19'h0;
      io_output_5_r_2 <= 19'h0;
      io_output_6_r <= 19'h0;
      io_output_6_r_1 <= 19'h0;
      io_output_7_r <= 19'h0;
    end
    else begin
      io_output_0_r <= io_input_0;
      io_output_0_r_1 <= io_output_0_r;
      io_output_0_r_2 <= io_output_0_r_1;
      io_output_0_r_3 <= io_output_0_r_2;
      io_output_0_r_4 <= io_output_0_r_3;
      io_output_0_r_5 <= io_output_0_r_4;
      io_output_0_r_6 <= io_output_0_r_5;
      io_output_0_r_7 <= io_output_0_r_6;
      io_output_1_r <= io_input_1;
      io_output_1_r_1 <= io_output_1_r;
      io_output_1_r_2 <= io_output_1_r_1;
      io_output_1_r_3 <= io_output_1_r_2;
      io_output_1_r_4 <= io_output_1_r_3;
      io_output_1_r_5 <= io_output_1_r_4;
      io_output_1_r_6 <= io_output_1_r_5;
      io_output_2_r <= io_input_2;
      io_output_2_r_1 <= io_output_2_r;
      io_output_2_r_2 <= io_output_2_r_1;
      io_output_2_r_3 <= io_output_2_r_2;
      io_output_2_r_4 <= io_output_2_r_3;
      io_output_2_r_5 <= io_output_2_r_4;
      io_output_3_r <= io_input_3;
      io_output_3_r_1 <= io_output_3_r;
      io_output_3_r_2 <= io_output_3_r_1;
      io_output_3_r_3 <= io_output_3_r_2;
      io_output_3_r_4 <= io_output_3_r_3;
      io_output_4_r <= io_input_4;
      io_output_4_r_1 <= io_output_4_r;
      io_output_4_r_2 <= io_output_4_r_1;
      io_output_4_r_3 <= io_output_4_r_2;
      io_output_5_r <= io_input_5;
      io_output_5_r_1 <= io_output_5_r;
      io_output_5_r_2 <= io_output_5_r_1;
      io_output_6_r <= io_input_6;
      io_output_6_r_1 <= io_output_6_r;
      io_output_7_r <= io_input_7;
    end
  end // always @(posedge)
  assign io_output_0 = io_output_0_r_7;
  assign io_output_1 = io_output_1_r_6;
  assign io_output_2 = io_output_2_r_5;
  assign io_output_3 = io_output_3_r_4;
  assign io_output_4 = io_output_4_r_3;
  assign io_output_5 = io_output_5_r_2;
  assign io_output_6 = io_output_6_r_1;
  assign io_output_7 = io_output_7_r;
endmodule

