// Generated by CIRCT firtool-1.62.0
module pre_processor_a(
  input        clock,
               reset,
  input  [7:0] io_input_0,
               io_input_1,
               io_input_2,
               io_input_3,
               io_input_4,
               io_input_5,
               io_input_6,
               io_input_7,
  output [7:0] io_output_0,
               io_output_1,
               io_output_2,
               io_output_3,
               io_output_4,
               io_output_5,
               io_output_6,
               io_output_7
);

  reg [7:0] io_output_0_REG;
  reg [7:0] io_output_1_REG;
  reg [7:0] io_output_2_REG;
  reg [7:0] io_output_3_REG;
  reg [7:0] io_output_4_REG;
  reg [7:0] io_output_5_REG;
  reg [7:0] io_output_6_REG;
  reg [7:0] io_output_7_REG;
  always @(posedge clock) begin
    if (reset) begin
      io_output_0_REG <= 8'h0;
      io_output_1_REG <= 8'h0;
      io_output_2_REG <= 8'h0;
      io_output_3_REG <= 8'h0;
      io_output_4_REG <= 8'h0;
      io_output_5_REG <= 8'h0;
      io_output_6_REG <= 8'h0;
      io_output_7_REG <= 8'h0;
    end
    else begin
      io_output_0_REG <= io_input_0;
      io_output_1_REG <= io_input_1;
      io_output_2_REG <= io_input_2;
      io_output_3_REG <= io_input_3;
      io_output_4_REG <= io_input_4;
      io_output_5_REG <= io_input_5;
      io_output_6_REG <= io_input_6;
      io_output_7_REG <= io_input_7;
    end
  end // always @(posedge)
  assign io_output_0 = io_output_0_REG;
  assign io_output_1 = io_output_1_REG;
  assign io_output_2 = io_output_2_REG;
  assign io_output_3 = io_output_3_REG;
  assign io_output_4 = io_output_4_REG;
  assign io_output_5 = io_output_5_REG;
  assign io_output_6 = io_output_6_REG;
  assign io_output_7 = io_output_7_REG;
endmodule

