// Generated by CIRCT firtool-1.62.0
module pre_processor_b(
  input        clock,
               reset,
  input  [7:0] io_input_0,
               io_input_1,
               io_input_2,
               io_input_3,
               io_input_4,
               io_input_5,
               io_input_6,
               io_input_7,
  output [7:0] io_output_0,
               io_output_1,
               io_output_2,
               io_output_3,
               io_output_4,
               io_output_5,
               io_output_6,
               io_output_7
);

  reg [7:0] io_output_0_r;
  reg [7:0] io_output_1_r;
  reg [7:0] io_output_1_r_1;
  reg [7:0] io_output_2_r;
  reg [7:0] io_output_2_r_1;
  reg [7:0] io_output_2_r_2;
  reg [7:0] io_output_3_r;
  reg [7:0] io_output_3_r_1;
  reg [7:0] io_output_3_r_2;
  reg [7:0] io_output_3_r_3;
  reg [7:0] io_output_4_r;
  reg [7:0] io_output_4_r_1;
  reg [7:0] io_output_4_r_2;
  reg [7:0] io_output_4_r_3;
  reg [7:0] io_output_4_r_4;
  reg [7:0] io_output_5_r;
  reg [7:0] io_output_5_r_1;
  reg [7:0] io_output_5_r_2;
  reg [7:0] io_output_5_r_3;
  reg [7:0] io_output_5_r_4;
  reg [7:0] io_output_5_r_5;
  reg [7:0] io_output_6_r;
  reg [7:0] io_output_6_r_1;
  reg [7:0] io_output_6_r_2;
  reg [7:0] io_output_6_r_3;
  reg [7:0] io_output_6_r_4;
  reg [7:0] io_output_6_r_5;
  reg [7:0] io_output_6_r_6;
  reg [7:0] io_output_7_r;
  reg [7:0] io_output_7_r_1;
  reg [7:0] io_output_7_r_2;
  reg [7:0] io_output_7_r_3;
  reg [7:0] io_output_7_r_4;
  reg [7:0] io_output_7_r_5;
  reg [7:0] io_output_7_r_6;
  reg [7:0] io_output_7_r_7;
  always @(posedge clock) begin
    if (reset) begin
      io_output_0_r <= 8'h0;
      io_output_1_r <= 8'h0;
      io_output_1_r_1 <= 8'h0;
      io_output_2_r <= 8'h0;
      io_output_2_r_1 <= 8'h0;
      io_output_2_r_2 <= 8'h0;
      io_output_3_r <= 8'h0;
      io_output_3_r_1 <= 8'h0;
      io_output_3_r_2 <= 8'h0;
      io_output_3_r_3 <= 8'h0;
      io_output_4_r <= 8'h0;
      io_output_4_r_1 <= 8'h0;
      io_output_4_r_2 <= 8'h0;
      io_output_4_r_3 <= 8'h0;
      io_output_4_r_4 <= 8'h0;
      io_output_5_r <= 8'h0;
      io_output_5_r_1 <= 8'h0;
      io_output_5_r_2 <= 8'h0;
      io_output_5_r_3 <= 8'h0;
      io_output_5_r_4 <= 8'h0;
      io_output_5_r_5 <= 8'h0;
      io_output_6_r <= 8'h0;
      io_output_6_r_1 <= 8'h0;
      io_output_6_r_2 <= 8'h0;
      io_output_6_r_3 <= 8'h0;
      io_output_6_r_4 <= 8'h0;
      io_output_6_r_5 <= 8'h0;
      io_output_6_r_6 <= 8'h0;
      io_output_7_r <= 8'h0;
      io_output_7_r_1 <= 8'h0;
      io_output_7_r_2 <= 8'h0;
      io_output_7_r_3 <= 8'h0;
      io_output_7_r_4 <= 8'h0;
      io_output_7_r_5 <= 8'h0;
      io_output_7_r_6 <= 8'h0;
      io_output_7_r_7 <= 8'h0;
    end
    else begin
      io_output_0_r <= io_input_0;
      io_output_1_r <= io_input_1;
      io_output_1_r_1 <= io_output_1_r;
      io_output_2_r <= io_input_2;
      io_output_2_r_1 <= io_output_2_r;
      io_output_2_r_2 <= io_output_2_r_1;
      io_output_3_r <= io_input_3;
      io_output_3_r_1 <= io_output_3_r;
      io_output_3_r_2 <= io_output_3_r_1;
      io_output_3_r_3 <= io_output_3_r_2;
      io_output_4_r <= io_input_4;
      io_output_4_r_1 <= io_output_4_r;
      io_output_4_r_2 <= io_output_4_r_1;
      io_output_4_r_3 <= io_output_4_r_2;
      io_output_4_r_4 <= io_output_4_r_3;
      io_output_5_r <= io_input_5;
      io_output_5_r_1 <= io_output_5_r;
      io_output_5_r_2 <= io_output_5_r_1;
      io_output_5_r_3 <= io_output_5_r_2;
      io_output_5_r_4 <= io_output_5_r_3;
      io_output_5_r_5 <= io_output_5_r_4;
      io_output_6_r <= io_input_6;
      io_output_6_r_1 <= io_output_6_r;
      io_output_6_r_2 <= io_output_6_r_1;
      io_output_6_r_3 <= io_output_6_r_2;
      io_output_6_r_4 <= io_output_6_r_3;
      io_output_6_r_5 <= io_output_6_r_4;
      io_output_6_r_6 <= io_output_6_r_5;
      io_output_7_r <= io_input_7;
      io_output_7_r_1 <= io_output_7_r;
      io_output_7_r_2 <= io_output_7_r_1;
      io_output_7_r_3 <= io_output_7_r_2;
      io_output_7_r_4 <= io_output_7_r_3;
      io_output_7_r_5 <= io_output_7_r_4;
      io_output_7_r_6 <= io_output_7_r_5;
      io_output_7_r_7 <= io_output_7_r_6;
    end
  end // always @(posedge)
  assign io_output_0 = io_output_0_r;
  assign io_output_1 = io_output_1_r_1;
  assign io_output_2 = io_output_2_r_2;
  assign io_output_3 = io_output_3_r_3;
  assign io_output_4 = io_output_4_r_4;
  assign io_output_5 = io_output_5_r_5;
  assign io_output_6 = io_output_6_r_6;
  assign io_output_7 = io_output_7_r_7;
endmodule

